### PR TITLE
Adding files inherited from the TypeScript example

### PR DESCRIPTION
**Pull request by t0yv0**
Fixes https://github.com/pulumi/pulumi/issues/6487

@justinvp

Any tips on testing the tarballs? how does pulumi install plugin from the tarballs? I could cook a make target; but I worry about venv whether it's included or not; including it in plugin is not a great idea since venv contents are platform specific (win vs linux vs darwin). I'm not sure without testing if pulumi can recognize a plugin to be python one and restore venv.

Some notes/todos for myself:

- [x] can we maybe avoid checking in the generated SDK code so the repo looks cleaner? or there are code search benefits for checking in the SDK. *Answer*: we look at gen code for search and diff

- [x] fixup all pulumi refs to 3.x.x

- [x] make target for tarball packaging; update REAMDE on packaging; test that packages are functional that is Pulumi recognizes them

For later:

- [ ] can we move python sources higher in the repo?

- [ ] should we edit the `construct` protocol to be `async`? requires change to pulumi.. if we need it later, it may become breaking

- [ ] the gen* program is Go is non-specific, we could move it to a tool outside this repo and keep the repo cleaner

### CODE REVIEW

**Comment by justinvp** [comment]
> Any tips on testing the tarballs? how does pulumi install plugin from the tarballs? I could cook a make target; but I worry about venv whether it's included or not; including it in plugin is not a great idea since venv contents are platform specific (win vs linux vs darwin). I'm not sure without testing if pulumi can recognize a plugin to be python one and restore venv.

For now, like with the TS boilerplate repo, I'd just make it so `make install_provider` makes the provider available in the top-level `bin` dir with an already created `venv`, with the `pulumi-resource-xyz` and `pulumi-resource-xyz.cmd` scripts that launch `python` from `venv`. I'd also update the `PulumiPlugin.yaml` file (like the one in the TS boilerplate) to have `runtime: python`. And then in the `README.md`, we'll recommend setting `PATH` to `bin` (like the TS boilerplate). And also copy over a `requirements.txt` into the `bin` dir.

As a follow-up, we are going to want to add make targets to all the boilerplate repos that will generate the tarballs. We won't want to include the `venv` dir in the tarball itself, but we will want to ensure the tarball has `PulumiPlugin.yaml` with `runtime: python` and a `requirements.txt`. When the tarball has `PulumiPlugin.yaml` with `runtime: python`, it will automatically create a venv and install dependencies into it from `requirements.txt` when the tarball is installed. (Similarly, if it is `runtime: node`, it'll run `npm install` when the tarball is installed).

https://github.com/pulumi/pulumi/blob/f11e8603a22aa7492985de46e8a32a4d0a88c0b7/sdk/go/common/workspace/plugins.go#L377-L395

I've actually never used it, but it looks like we have `pulumi plugin install --file` for installing a tarball from a file rather than downloading it.

> 2\. can we maybe avoid checking in the generated SDK code so the
>     repo looks cleaner? or there are code search benefits for
>     checking in the SDK

Possibly. We've tried this in the past for our own providers, but found it very difficult to understand the diff when adopting new changes, and also the downside of searchability, as you mention. We could consider it for boilerplate repos.

> 3\. the gen* program is Go is non-specific, we could move it to a
>     tool outside this repo and keep the repo cleaner

I think we'll probably end up doing this soon. Either a separate tool or we've also talked about potentially a CLI command like `pulumi generate` that could do it.

**Comment by t0yv0** [comment]
That was a great pointer. I added a Make target to build the tarballs, and tested them out with `pulumi plugin install --file`. Had to make a few changes but now it works as advertised. During `pulumi install` Pulumi uses system python and restores venv - so we do not need to redist pulumi SDK and deps. We only distribute the plugin sources. 

I feel like we may have some exciting failure scenarios in the future where the venv and the python version managed by Pulumi depends on external choice of python version, but we can deal with it as it comes. Python seems to have new tools like `poetry`  emerging to pin and virtualize python itself but there's far from a consensus on what is the canonical tool.

**Comment by t0yv0** [comment]
Ok so this looks good to me  - ready for review please. I will just work now to fixup all package refs to refer to brand new 3xx things.

**Comment by t0yv0** [comment]
Package refs updated, example still works. Strange can't add `@justinvp` to reviewers on the repo, something with GitHub .

**Comment by justinvp** [comment]
> Strange can't add `@justinvp` to reviewers on the repo, something with GitHub

Weird. I'll review in a little bit.

**Review by justinvp — APPROVED** [review]
LGTM

**Comment by justinvp** [comment]
@t0yv0, do you want to add a commit that adopts the codegen fix to this PR? Like https://github.com/pulumi/pulumi-component-provider-ts-boilerplate/pull/3?

**Comment by t0yv0** [comment]
I'll follow up with another PR on codegen fix.

**Pull request merged**
